import puppeteer from 'puppeteer-core';
const b = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: 'new', args: ['--use-angle=swiftshader'] });
const page = await b.newPage();
const sleep = ms => new Promise(r => setTimeout(r, ms));
await page.goto('http://localhost:4173/', { waitUntil: 'networkidle2' });
await sleep(3000);
const cdp = await page.createCDPSession();
const manifest = await cdp.send('Page.getAppManifest');
console.log('manifest errors', JSON.stringify(manifest.errors), 'url', manifest.url);
const inst = await cdp.send('Page.getInstallabilityErrors');
console.log('installability', JSON.stringify(inst.installabilityErrors));
console.log('sw', await page.evaluate(async () => { const r = await navigator.serviceWorker.getRegistration(); return r ? r.active?.state ?? 'sem active' : 'nenhum'; }));
await page.reload({ waitUntil: 'networkidle2' });
await sleep(2000);
console.log('controlado', await page.evaluate(() => !!navigator.serviceWorker.controller));
console.log('cache', await page.evaluate(async () => (await (await caches.open('dogcity-v1')).keys()).length));
await page.setOfflineMode(true);
await page.reload({ waitUntil: 'domcontentloaded' });
await sleep(4000);
console.log('offline texto', JSON.stringify(await page.evaluate(() => document.body.innerText.slice(0, 120))));
await page.screenshot({ path: 'offline.png' });
await b.close();
